include ../shared.mk

SOURCES:=$(wildcard *.c)
CFLAGS+=-I${PROJECT_ROOT}/external/scpi-parser/libscpi/inc/

EXTERNAL_LIBS+=${PROJECT_ROOT}/external/scpi-parser/libscpi/dist/libscpi.a

include ../end.mk

